# Generated by Django 3.2 on 2021-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievementsapp', '0002_achievementmodel_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
