# Generated by Django 3.2 on 2021-06-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementsapp', '0003_auto_20210610_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementsmodel',
            name='company_logo',
        ),
    ]
