# Generated by Django 3.2 on 2021-06-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementsapp', '0004_remove_placementsmodel_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='company_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='company_logos/'),
        ),
    ]
