# Generated by Django 3.2 on 2021-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0004_auto_20210609_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
