# Generated by Django 3.2 on 2021-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0006_auto_20210609_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='organiser',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='organiser',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
