# Generated by Django 3.2 on 2021-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0008_alter_eventmodel_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.eventmodel')),
            ],
        ),
    ]
